### ISSUE TITLE
Better design

### ISSUE THREAD

**Issue by arctouch-pietrocaselani** [pietrocaselani/CouchTracker#110]
Change the tabs to:
* TV Shows
* Movies
* Lists

Each tab shows a paginated control to display
* Watched (Only for TV shows)
* History
* Trending
* Popular

And change the design of the app, like colors and everything!

**Comment by pietrocaselani** [comment]
Closing this issue. I implemeted tabs. Some screenshots below.

<img width="504" alt="progress" src="https://user-images.githubusercontent.com/862516/35739114-bf778968-0817-11e8-93aa-0bcb56be9aa4.png">
<img width="504" alt="trendingmovies" src="https://user-images.githubusercontent.com/862516/35739115-bf9d5800-0817-11e8-93d9-27dfd0aa2c02.png">
<img width="504" alt="settings" src="https://user-images.githubusercontent.com/862516/35739116-bfbf1a62-0817-11e8-9f05-ce1bba4a7617.png">
<img width="504" alt="trendingshows" src="https://user-images.githubusercontent.com/862516/35739118-bfe5a916-0817-11e8-8ad9-d3f4edf21699.png">
<img width="504" alt="episode" src="https://user-images.githubusercontent.com/862516/35739119-c009a58c-0817-11e8-80b1-c11beeec7c39.png">
